# Generated by Django 4.2.10 on 2025-03-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistify', '0004_alter_dialog_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dialog',
        ),
    ]
